name: Run system update on Ubuntu
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Run apt update
      run: sudo apt update
    - name: Run apt upgrade
      run: sudo apt upgrade -y
